apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcp-server
  name: mcp-server-service
  namespace: mcp-server
spec:
  ports:
  - name: mcp-server-service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mcp-server
  type: ClusterIP
