apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - image: dominikjaro/fastapi:v1.0.5
        imagePullPolicy: Always
        name: backend-api
        env:
        - name: DATABASE_HOSTNAME
          value: postgres-service.postgres.svc.cluster.local
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: MCP_SERVER_URL
          value: http://mcp-server.mcp-server:8080
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-credentials
              key: GEMINI_API_KEY
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-client-id
              key: GOOGLE_CLIENT_ID
        - name: ALLOWED_USERS
          valueFrom:
            secretKeyRef:
              name: allowed-users
              key: ALLOWED_USERS
        - name: DATABASE_URL
          value: postgresql://trainingchef_admin:$(POSTGRES_PASSWORD)@postgres-service.postgres.svc.cluster.local:5432/trainingchef_db
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits: 
            memory: "256Mi"
            cpu: "1000m" 