apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-ui
  name: frontend-ui
  namespace: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - image: dominikjaro/training-chef-app-frontend:latest
        name: frontend-ui
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: 256Mi
          requests:
            cpu: "100m"
            memory: 64Mi
status: {}