apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ui-ingress
  namespace: frontend-ui
spec:
  ingressClassName: nginx
  rules:
  - host: trainingchef.cc
    http:
      paths:
      - backend:
          service:
            name: frontend-ui-service
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}