apiVersion: v1
items:
- apiVersion: v1
  data:
    token: [REDACTED] # cloudflare tunnel token for k8s-ingress-tunnel-prod
  kind: Secret
  metadata:
    creationTimestamp: "2025-12-15T14:36:59Z"
    name: cloudflare-ingress-tunnel-prod-token
    namespace: cloudflare-tunnel
    resourceVersion: "40759"
    uid: 4050dcc3-bb77-42e2-99f3-5251920fb3c1
  type: Opaque
kind: List
metadata:
  resourceVersion: ""